<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
   
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.1" />
   
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FilmKirala.Infrastructure\FilmKirala.Infrastructure.csproj" />
    <ProjectReference Include="..\FilmKirala.Shared\FilmKirala.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
  </ItemGroup>

</Project>
